name: Build
on: 
  push:
    - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: docs/main.tex

   build-docker:
     runs-on: ubuntu-latest
     steps:
       - name: Set up Git repository
         uses: actions/checkout@v2
       - name: Build Image
         run: docker build -t felipefrocha89/esufmg:labiv .
       - name: Test Image
         run:  docker run --rm -i -v $PWD:/app -w /app felipefrocha89/esufmg:labiv
       - name: Deploy Docker
         run: echo {{ secrets.DOCKER_PASSWD }} | docker login -u felipefrocha89 --password-stdin
