name: Build

on:
  push:
    branches:
      - main
      - feature/*
jobs:
  latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: docs
          root_file: |
            - main.tex
      
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: docs/main.pdf

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
   
      - name: Build Image
        run: docker build -t felipefrocha89/esufmg:labiv .
            
      - name: Deploy Docker
        run: echo {{ secrets.DOCKER_PASSWD }} | docker login -u felipefrocha89 --password-stdin
